# This policy verifies the installation of Integrity Shield on the managed clusters.
# 
# "enforce", it will install Integirty Shield operator

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-integrity-shield
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-5 Access Restrictions for Change
    integrityshield.io/message: H4sIABLGPWAAA+1Z3W/bNhB/919BOG9DqKTYAmx687xh60MzI876svaBps4yF4nUSMqLV/R/35GUZFsfjpM4xTJUKJKGvO/73fEonZHblTCkUJngG7IGLZYCDLErIEIay7KMWaEkUUvyVlpItbAbMl8JyBKCy44uZ5KlkBCelcaCNtHojOC/Mcil0hzG50RY8rfIslpikCT0jqQCNLNKj0asEO9RBqqMK6Mi3JS0Ek6DshykjYS6WL8Z3QmZxGTmSUc5WJYwy+IRIZLlUMugoradGq8R95mUynrnjCMnR6hD62XCdGJicv12fkvmM/L95SW9+vZIfs7QCqUxwDGZviNTJZciLXWI8LuG9FhpSlqtMi+LXpEJ52AMuQFjteDeL4IJINMVkymMTAHc+amRPxFe5cRTxaRKFG4mwrBFBhjQJcuMW6niZyEvEAngQ0WJWvwJ3P4ESyGFl+FNxpg+NnuBLeRwLxxVQsP+blrDczC51O2agnmX3FP7Hp7hCJAzD+iWz5496nARLBuFBaNFkoAki03g1cCRTqakYBrNQK/JmmUl+Fz0S4oa0wy4CrSbmPwq0lWzHMK9n4TwUMIVLgomOdxuCoxJjpFesTU0JGQwW7vBv26FrJvPJltDOdnNTCcldYVTs0Ek5K8BRSp9vfBZfTH47CarTrKJuNKg3K/8ooWbkKXfKspftCqLJ+GqAVTaERGIPZqPQuL22c90eCzTKdimPkx7n/4vwG7KxVe0b9mfgXaWFSvWh/l5uTBci8JJPUUrfUHMc5wZJGQx8c60NqspbpYxOSkKrTBjMZmUVuWYJv4sH4wqtXMAI5mXcrfMTS/l9dZnVzQofGmxYvQdWEx+6zBDJqxli3Cbzt8fsClaX0Zvou9eQ9Vy/bVot+zHFC3+30RNHEMYQ4oG67a598zrq8P2eWTpGtDo/gsWbqbSFHR7FWs2RzjG5K+SbZy3A1i96Oh38jDVcV0Re/q9M6fTVcnrU8WWPrOImk+f21Z45lBSXVv8hXYTcFOkBcL//uryh67JIbWTJBfyd7Tj2qdvHIIeO8MEB8a5KqWNBxyi+Nv9TBLE2V3YzqBaoKHiuNXZuKtdzjkKbZrZHDJEs+oJraNFzQn0bVEy/qYrnBC4P8RyVy6A9vLh5rapdiiMSCXoobh7d0V3WHJS5eAodciLoG+IZc6wR8Dc03S5KTEuwJjRacjLqRUM8tKqEzzAj60GNlUsifGkNMikuMH9Rp/Jpe97AzZDzgSezN1wbnV1Rtlg7bEWGOA6jMaxE6qxU9Cw1iLVEM5r5z8SzbRaiqxvlN477rRpz/UILK0sunxT9rA7ATiD8FV/PLD1++vGESd2t0RTiTPeU7SW2D3kk9tJPFCZz5NaNake2X5ImK6A333pCLtn711eZxOlqFz8AzNmUZz8TxkXTvGZxgnk3pVc1A1tKSvsTqztbxUvZjzr1+gbWz3BRDvvQ6MPY1YU5tBIu1LGTdI0gSJTG/fS8MN44BB5pgazc206tQ6zkZyG1nRq0TglK8mxy+EMd5zpGVtA5kQf8eq3WnWgezHB/ow+qXStlK0moT65rTcth8Ygr/QQAQnV9PM9XleM2b7k73qCB9cxdzhhqtmh/03p9qlHdndxGCDx1yUTkz/GVpcw/jiilD75y4e757rVH/FPrJeebyCLsEOHvoUUtYgbWO58OalXB/mantjw45kxIjvN6oEiGW0HGPrg95pW/31MR2yH96Ha7QbXe9bzdenBGNWXtEoRzl2JaL45UfdGwpaIhPGtA4KHi/WXlfA1KJm22CZrnOlct92K3K+CftRT8snDHORaaCWdxed7QD3fwWQC6/HHz6N/AVlm148aHAAA
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRRktCQUFCQ0FBMEZpRUVxcmJ2dEJ4WFBkV3pLMFVWaUxlV0JCQXJ3SmdGQW1BOXhoSVdISE5wWjI1bGNrQmwKYm5SbGNuQnlhWE5sTG1OdmJRQUtDUkNJdDVZRUVDdkFtSEo0Qi80MlNNOHJ6ZTZUNGJCWlRqS1FKYytZN2NYRwpFKzVQRzZVQW1RSDk0alMya0hFK1hpZlJZS3BrZHJSRElSSG9nRzdOTkh5UFp0VU9nZjgyWFdKK1JOR1pGV3dzCmxDWlNXSHVCVC81cTVsdU5KbC9zQVVLbWxkaCsreTlIL2kzT01VaHVkY1AzcW5NMU04RVVwUzhSQ3ZmaWdhalMKaEJKQUtLRnl1UFEvb2dhQXFQcUptRXoyUVBWM0l4OG9rbWMyREtoL0FRcDhJQVV4WnMvYjRBalgyVzV2NW5xcApMRlRwWEtjWHNKdFNtUmhJUmVjT1E0WjR1cnFzRTdUUDVSeWZGNCtWdjZLdy9GUUZaUGpTYXBaZmZ4c0JRSU5RCjhZOTIyMFpSaGxOTU45Rkw4M2tldTAva1lac3lkck9nSU9ZY2NJVDhWYTRTRDJySitJVVJCSlkzZDJURwo9VEZPVAotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-integrity-shield-namespace
      spec:
        remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
        severity: High
        object-templates:
        - complianceType: musthave
          objectDefinition:
            kind: Namespace
            apiVersion: v1
            metadata:
              name: integrity-shield-operator-system
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-integrity-shield-og
      spec:
        remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              name: integrity-operator-group
              namespace: integrity-shield-operator-system
            spec:
              targetNamespaces:
              - integrity-shield-operator-system
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-integrity-shield-sub
      spec:
        remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: integrity-shield-operator
              namespace: integrity-shield-operator-system
            spec:
              channel: alpha
              installPlanApproval: Automatic
              name: integrity-shield-operator
              source: community-operators
              sourceNamespace: openshift-marketplace
              startingCSV: integrity-shield-operator.v0.1.4
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-integrity-shield-cr
      spec:
        remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: apis.integrityshield.io/v1alpha1
            kind: IntegrityShield
            metadata:
              name: integrity-shield-server
              namespace: integrity-shield-operator-system
            spec:
              logger:
                image: quay.io/open-cluster-management/integrity-shield-logging:0.1.4
              server:
                image: quay.io/open-cluster-management/integrity-shield-server:0.1.4
              affinity: {}
              shieldConfig:
                verifyType: pgp # x509
                iShieldAdminUserName: "system:serviceaccount:open-cluster-management-agent-addon:klusterlet-addon-policyctrl"
                inScopeNamespaceSelector:
                  include:
                  - "*"
                  exclude:
                  - "kube-*"
                  - "openshift-*"
              signerConfig:
                policies:
                - namespaces:
                  - "*"
                  signers:
                  - "SampleSigner"
                - scope: "Cluster"
                  signers:
                  - "SampleSigner"
                signers:
                - name: "SampleSigner"
                  keyConfig: sample-signer-keyconfig
                  subjects:
                  - email: "*"
              keyConfig:
              - name: sample-signer-keyconfig
                secretName: keyring-secret
              resourceSigningProfiles:
              - name: policy-rsp
                protectRules:
                - match:
                  - apiGroup: policy.open-cluster-management.io
                ignoreRules:
                - match:
                  - username: "system:serviceaccount:open-cluster-management-agent:*"
                  - username: "system:serviceaccount:open-cluster-management-agent-addon:*"
                forceCheckRules:
                - match:
                  - apiGroup: policy.open-cluster-management.io
                    kind: Policy
                kustomizePatterns:
                - match:
                  - apiGroup: policy.open-cluster-management.io
                    kind: Policy
                  namePrefix: "*."
                unprotectAttrs:
                - match:
                  - apiGroup: policy.open-cluster-management.io
                  attrs:
                  - "metadata.annotations.\"apps.open-cluster-management.io/hosting-deployable\""
                  - "metadata.annotations.\"apps.open-cluster-management.io/hosting-subscription\""
                  - "metadata.annotations.\"apps.open-cluster-management.io/sync-source\""
                  - "metadata.annotations.\"apps.open-cluster-management.io/reconcile-option\""
                  - "metadata.labels.\"policy.open-cluster-management.io/cluster-name\""
                  - "metadata.labels.\"policy.open-cluster-management.io/cluster-namespace\""
                  - "metadata.labels.\"policy.open-cluster-management.io/root-policy\""
                targetNamespaceSelector:
                  labelSelector:
                    matchExpressions:
                    - key: policy.open-cluster-management.io/isClusterNamespace
                      operator: In
                      values: ["true"]
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-integrity-shield
  annotations:
    integrityshield.io/message: H4sIABLGPWAAA+1Z3W/bNhB/919BOG9DqKTYAmx687xh60MzI876svaBps4yF4nUSMqLV/R/35GUZFsfjpM4xTJUKJKGvO/73fEonZHblTCkUJngG7IGLZYCDLErIEIay7KMWaEkUUvyVlpItbAbMl8JyBKCy44uZ5KlkBCelcaCNtHojOC/Mcil0hzG50RY8rfIslpikCT0jqQCNLNKj0asEO9RBqqMK6Mi3JS0Ek6DshykjYS6WL8Z3QmZxGTmSUc5WJYwy+IRIZLlUMugoradGq8R95mUynrnjCMnR6hD62XCdGJicv12fkvmM/L95SW9+vZIfs7QCqUxwDGZviNTJZciLXWI8LuG9FhpSlqtMi+LXpEJ52AMuQFjteDeL4IJINMVkymMTAHc+amRPxFe5cRTxaRKFG4mwrBFBhjQJcuMW6niZyEvEAngQ0WJWvwJ3P4ESyGFl+FNxpg+NnuBLeRwLxxVQsP+blrDczC51O2agnmX3FP7Hp7hCJAzD+iWz5496nARLBuFBaNFkoAki03g1cCRTqakYBrNQK/JmmUl+Fz0S4oa0wy4CrSbmPwq0lWzHMK9n4TwUMIVLgomOdxuCoxJjpFesTU0JGQwW7vBv26FrJvPJltDOdnNTCcldYVTs0Ek5K8BRSp9vfBZfTH47CarTrKJuNKg3K/8ooWbkKXfKspftCqLJ+GqAVTaERGIPZqPQuL22c90eCzTKdimPkx7n/4vwG7KxVe0b9mfgXaWFSvWh/l5uTBci8JJPUUrfUHMc5wZJGQx8c60NqspbpYxOSkKrTBjMZmUVuWYJv4sH4wqtXMAI5mXcrfMTS/l9dZnVzQofGmxYvQdWEx+6zBDJqxli3Cbzt8fsClaX0Zvou9eQ9Vy/bVot+zHFC3+30RNHEMYQ4oG67a598zrq8P2eWTpGtDo/gsWbqbSFHR7FWs2RzjG5K+SbZy3A1i96Oh38jDVcV0Re/q9M6fTVcnrU8WWPrOImk+f21Z45lBSXVv8hXYTcFOkBcL//uryh67JIbWTJBfyd7Tj2qdvHIIeO8MEB8a5KqWNBxyi+Nv9TBLE2V3YzqBaoKHiuNXZuKtdzjkKbZrZHDJEs+oJraNFzQn0bVEy/qYrnBC4P8RyVy6A9vLh5rapdiiMSCXoobh7d0V3WHJS5eAodciLoG+IZc6wR8Dc03S5KTEuwJjRacjLqRUM8tKqEzzAj60GNlUsifGkNMikuMH9Rp/Jpe97AzZDzgSezN1wbnV1Rtlg7bEWGOA6jMaxE6qxU9Cw1iLVEM5r5z8SzbRaiqxvlN477rRpz/UILK0sunxT9rA7ATiD8FV/PLD1++vGESd2t0RTiTPeU7SW2D3kk9tJPFCZz5NaNake2X5ImK6A333pCLtn711eZxOlqFz8AzNmUZz8TxkXTvGZxgnk3pVc1A1tKSvsTqztbxUvZjzr1+gbWz3BRDvvQ6MPY1YU5tBIu1LGTdI0gSJTG/fS8MN44BB5pgazc206tQ6zkZyG1nRq0TglK8mxy+EMd5zpGVtA5kQf8eq3WnWgezHB/ow+qXStlK0moT65rTcth8Ygr/QQAQnV9PM9XleM2b7k73qCB9cxdzhhqtmh/03p9qlHdndxGCDx1yUTkz/GVpcw/jiilD75y4e757rVH/FPrJeebyCLsEOHvoUUtYgbWO58OalXB/mantjw45kxIjvN6oEiGW0HGPrg95pW/31MR2yH96Ha7QbXe9bzdenBGNWXtEoRzl2JaL45UfdGwpaIhPGtA4KHi/WXlfA1KJm22CZrnOlct92K3K+CftRT8snDHORaaCWdxed7QD3fwWQC6/HHz6N/AVlm148aHAAA
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRRktCQUFCQ0FBMEZpRUVxcmJ2dEJ4WFBkV3pLMFVWaUxlV0JCQXJ3SmdGQW1BOXhoSVdISE5wWjI1bGNrQmwKYm5SbGNuQnlhWE5sTG1OdmJRQUtDUkNJdDVZRUVDdkFtSEo0Qi80MlNNOHJ6ZTZUNGJCWlRqS1FKYytZN2NYRwpFKzVQRzZVQW1RSDk0alMya0hFK1hpZlJZS3BrZHJSRElSSG9nRzdOTkh5UFp0VU9nZjgyWFdKK1JOR1pGV3dzCmxDWlNXSHVCVC81cTVsdU5KbC9zQVVLbWxkaCsreTlIL2kzT01VaHVkY1AzcW5NMU04RVVwUzhSQ3ZmaWdhalMKaEJKQUtLRnl1UFEvb2dhQXFQcUptRXoyUVBWM0l4OG9rbWMyREtoL0FRcDhJQVV4WnMvYjRBalgyVzV2NW5xcApMRlRwWEtjWHNKdFNtUmhJUmVjT1E0WjR1cnFzRTdUUDVSeWZGNCtWdjZLdy9GUUZaUGpTYXBaZmZ4c0JRSU5RCjhZOTIyMFpSaGxOTU45Rkw4M2tldTAva1lac3lkck9nSU9ZY2NJVDhWYTRTRDJySitJVVJCSlkzZDJURwo9VEZPVAotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
placementRef:
  name: placement-policy-integrity-shield
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-integrity-shield
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-integrity-shield
  annotations:
    integrityshield.io/message: H4sIABLGPWAAA+1Z3W/bNhB/919BOG9DqKTYAmx687xh60MzI876svaBps4yF4nUSMqLV/R/35GUZFsfjpM4xTJUKJKGvO/73fEonZHblTCkUJngG7IGLZYCDLErIEIay7KMWaEkUUvyVlpItbAbMl8JyBKCy44uZ5KlkBCelcaCNtHojOC/Mcil0hzG50RY8rfIslpikCT0jqQCNLNKj0asEO9RBqqMK6Mi3JS0Ek6DshykjYS6WL8Z3QmZxGTmSUc5WJYwy+IRIZLlUMugoradGq8R95mUynrnjCMnR6hD62XCdGJicv12fkvmM/L95SW9+vZIfs7QCqUxwDGZviNTJZciLXWI8LuG9FhpSlqtMi+LXpEJ52AMuQFjteDeL4IJINMVkymMTAHc+amRPxFe5cRTxaRKFG4mwrBFBhjQJcuMW6niZyEvEAngQ0WJWvwJ3P4ESyGFl+FNxpg+NnuBLeRwLxxVQsP+blrDczC51O2agnmX3FP7Hp7hCJAzD+iWz5496nARLBuFBaNFkoAki03g1cCRTqakYBrNQK/JmmUl+Fz0S4oa0wy4CrSbmPwq0lWzHMK9n4TwUMIVLgomOdxuCoxJjpFesTU0JGQwW7vBv26FrJvPJltDOdnNTCcldYVTs0Ek5K8BRSp9vfBZfTH47CarTrKJuNKg3K/8ooWbkKXfKspftCqLJ+GqAVTaERGIPZqPQuL22c90eCzTKdimPkx7n/4vwG7KxVe0b9mfgXaWFSvWh/l5uTBci8JJPUUrfUHMc5wZJGQx8c60NqspbpYxOSkKrTBjMZmUVuWYJv4sH4wqtXMAI5mXcrfMTS/l9dZnVzQofGmxYvQdWEx+6zBDJqxli3Cbzt8fsClaX0Zvou9eQ9Vy/bVot+zHFC3+30RNHEMYQ4oG67a598zrq8P2eWTpGtDo/gsWbqbSFHR7FWs2RzjG5K+SbZy3A1i96Oh38jDVcV0Re/q9M6fTVcnrU8WWPrOImk+f21Z45lBSXVv8hXYTcFOkBcL//uryh67JIbWTJBfyd7Tj2qdvHIIeO8MEB8a5KqWNBxyi+Nv9TBLE2V3YzqBaoKHiuNXZuKtdzjkKbZrZHDJEs+oJraNFzQn0bVEy/qYrnBC4P8RyVy6A9vLh5rapdiiMSCXoobh7d0V3WHJS5eAodciLoG+IZc6wR8Dc03S5KTEuwJjRacjLqRUM8tKqEzzAj60GNlUsifGkNMikuMH9Rp/Jpe97AzZDzgSezN1wbnV1Rtlg7bEWGOA6jMaxE6qxU9Cw1iLVEM5r5z8SzbRaiqxvlN477rRpz/UILK0sunxT9rA7ATiD8FV/PLD1++vGESd2t0RTiTPeU7SW2D3kk9tJPFCZz5NaNake2X5ImK6A333pCLtn711eZxOlqFz8AzNmUZz8TxkXTvGZxgnk3pVc1A1tKSvsTqztbxUvZjzr1+gbWz3BRDvvQ6MPY1YU5tBIu1LGTdI0gSJTG/fS8MN44BB5pgazc206tQ6zkZyG1nRq0TglK8mxy+EMd5zpGVtA5kQf8eq3WnWgezHB/ow+qXStlK0moT65rTcth8Ygr/QQAQnV9PM9XleM2b7k73qCB9cxdzhhqtmh/03p9qlHdndxGCDx1yUTkz/GVpcw/jiilD75y4e757rVH/FPrJeebyCLsEOHvoUUtYgbWO58OalXB/mantjw45kxIjvN6oEiGW0HGPrg95pW/31MR2yH96Ha7QbXe9bzdenBGNWXtEoRzl2JaL45UfdGwpaIhPGtA4KHi/WXlfA1KJm22CZrnOlct92K3K+CftRT8snDHORaaCWdxed7QD3fwWQC6/HHz6N/AVlm148aHAAA
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRRktCQUFCQ0FBMEZpRUVxcmJ2dEJ4WFBkV3pLMFVWaUxlV0JCQXJ3SmdGQW1BOXhoSVdISE5wWjI1bGNrQmwKYm5SbGNuQnlhWE5sTG1OdmJRQUtDUkNJdDVZRUVDdkFtSEo0Qi80MlNNOHJ6ZTZUNGJCWlRqS1FKYytZN2NYRwpFKzVQRzZVQW1RSDk0alMya0hFK1hpZlJZS3BrZHJSRElSSG9nRzdOTkh5UFp0VU9nZjgyWFdKK1JOR1pGV3dzCmxDWlNXSHVCVC81cTVsdU5KbC9zQVVLbWxkaCsreTlIL2kzT01VaHVkY1AzcW5NMU04RVVwUzhSQ3ZmaWdhalMKaEJKQUtLRnl1UFEvb2dhQXFQcUptRXoyUVBWM0l4OG9rbWMyREtoL0FRcDhJQVV4WnMvYjRBalgyVzV2NW5xcApMRlRwWEtjWHNKdFNtUmhJUmVjT1E0WjR1cnFzRTdUUDVSeWZGNCtWdjZLdy9GUUZaUGpTYXBaZmZ4c0JRSU5RCjhZOTIyMFpSaGxOTU45Rkw4M2tldTAva1lac3lkck9nSU9ZY2NJVDhWYTRTRDJySitJVVJCSlkzZDJURwo9VEZPVAotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - {key: environment, operator: In, values: ["dev"]}
